[Chore #158839934] test when on fail

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -41,6 +41,7 @@ export_failure_determinant: &failure_determinant
     name: Export Failure Determinant
     command: |
       echo 'export INSTRUMENT_TEST_FAILURE=false' >> $BASH_ENV
+
 decode_gservices_key: &decode_gservices_key
   run:
     name: Decode Google Services JSON key
@@ -490,9 +491,15 @@ jobs:
           name: Notifying slack channel on fail
           when: on_fail
           command: |
-            echo ${INSTRUMENT_TEST_FAILURE} ${TERM} ===============
-            export ${INSTRUMENT_TEST_FAILURE}=true
-            bash ~/repo/.circleci/notify_slack_fail.sh
+            if [ ${INSTRUMENT_TEST_FAILURE} == false ]; then
+              bash ~/repo/.circleci/notify_slack_fail.sh
+            fi
+      - export_failure_determinant: &failure_determinant
+          run:
+            name: Modify Failure Determinant
+            when: on_success
+            command: |
+              echo 'export INSTRUMENT_TEST_FAILURE=true' >> $BASH_ENV
       - run:
           name: Run instrumented test on Firebase Test Lab
           command: gcloud firebase test android run --type instrumentation --app app/build/outputs/apk/mock/debug/app-mock-debug.apk --test app/build/outputs/apk/androidTest/mock/debug/app-mock-debug-androidTest.apk --device model=Nexus7,version=22,locale=en,orientation=landscape --environment-variables coverage=true,coverageFile=/sdcard/coverage.ec --directories-to-pull=/sdcard --timeout 20m
@@ -518,9 +525,10 @@ jobs:
           name: Download instrumented test results from Firebase Test Lab on fail fail
           when: on_fail
           command: |
-            echo ${INSTRUMENT_TEST_FAILURE} ${TERM} =================
-            mkdir firebase
-            gsutil -m cp -r -U "`gsutil ls gs://test-lab-42q965dw0t03q-w3crkis8m06h6 | tail -1`*" /root/repo/firebase/ || true
+            if [ ${INSTRUMENT_TEST_FAILURE} == true ]; then
+              mkdir firebase
+              gsutil -m cp -r -U "`gsutil ls gs://test-lab-42q965dw0t03q-w3crkis8m06h6 | tail -1`*" /root/repo/firebase/ || true
+            fi
       - store_artifacts:
           when: on_fail
           path: firebase/
@@ -529,7 +537,9 @@ jobs:
           name: Notifying slack channel on fail
           when: on_fail
           command: |
-            bash ~/repo/.circleci/notify_slack_fail.sh
+            if [ ${INSTRUMENT_TEST_FAILURE} == true ]; then
+              bash ~/repo/.circleci/notify_slack_fail.sh
+            fi
 
   report_coverage:
     <<: *defaults
